---
- name: Create folder mood2anime
  ansible.builtin.file:
    path: "./mood2anime2"
    mode: 0750
    state: directory
- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "files/docker-compose.yml"
    dest: "./mood2anime2/docker-compose.yml"
    mode: 0750