---
- name: Create folder mood2anime
  ansible.builtin.file:
    path: "./mood2anime2"
    mode: 0750
    state: directory
- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "files/docker-compose.yml"
    dest: "./mood2anime2/docker-compose.yml"
    mode: 0750
- name: Create folder mood2anime
  ansible.builtin.file:
    path: "./mood2anime2/includes"
    mode: 0750
    state: directory
- name: Template metrics.html
  ansible.builtin.template:
    src: "files/metrics.html"
    dest: "./mood2anime2/includes/metrics.html"
    mode: 0750
    owner: 101
- name: Create folder mood2anime
  ansible.builtin.file:
    path: "./mood2anime2/nginx/conf.d"
    mode: 0750
    state: directory
- name: Template mood2anime.conf
  ansible.builtin.template:
    src: "files/mood2anime.conf"
    dest: "./mood2anime2/nginx/conf.d/mood2anime.conf"
    mode: 0750