version: '3'
services:
  mood2anime:
    image: {{ docker_image }}
    restart: always
    user: "${UID}"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_CSRF_TRUSTED_ORIGINS={{DJANGO_CSRF_TRUSTED_ORIGINS}}
      - DJANGO_WEBSITE_DNS_NAME={{DJANGO_WEBSITE_DNS_NAME}}
    volumes:
      - static-content:/mood2anime/staticRoot
      - media-content:/mood2anime/media
      - ./includes:/mood2anime/templates/includes:ro
  nginx:
    image: nginx
    restart: always
    user: "${UID}"
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - static-content:/staticRoot
      - media-content:/mediaRoot
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
volumes:
  static-content:
  media-content:
