version: '3'
services:
  mood2anime:
    image: max0x15/mood2anime
    restart: always
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_CSRF_TRUSTED_ORIGINS={{DJANGO_CSRF_TRUSTED_ORIGINS}}
      - DJANGO_WEBSITE_DNS_NAME={{DJANGO_WEBSITE_DNS_NAME}}
    ports:
      - 8080:8080