version: '3'
services:
  mood2anime:
    image: {{ docker_image }}
    restart: always
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_CSRF_TRUSTED_ORIGINS={{DJANGO_CSRF_TRUSTED_ORIGINS}}
      - DJANGO_WEBSITE_DNS_NAME={{DJANGO_WEBSITE_DNS_NAME}}
    volumes:
      - static-content:/mood2anime/staticRoot
      - media-content:/mood2anime/media
      - ./includes:/mood2anime/templates/includes
volumes:
  static-content:
  media-content:
