version: '3'
services:
  mood2anime:
    image: {{ docker_image }}
    restart: always
    user: "${UID}"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_CSRF_TRUSTED_ORIGINS={{DJANGO_CSRF_TRUSTED_ORIGINS}}
      - DJANGO_WEBSITE_DNS_NAME={{DJANGO_WEBSITE_DNS_NAME}}
    volumes:
      - static-content:/mood2anime/staticRoot
      - media-content:/mood2anime/media
      - ./includes:/mood2anime/templates/includes:ro
      - ./mood2anime_db:/mood2anime_DB:ro
  nginx:
    image: nginx:latest
    restart: always
    user: "${UID}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-content:/staticRoot:ro
      - media-content:/mediaRoot:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - certbotwww:/certbot/www
      - certbotcerts:/certbotCerts
  certbot:
    image: certbot/certbot:latest
    entrypoint:
      - /bin/sh
    command:
      - /getCert.sh
      - {{DJANGO_WEBSITE_DNS_NAME}}
    volumes:
      - certbotwww:/certbot/www
      - certbotcerts:/etc/letsencrypt
      - ./getCert.sh:/getCert.sh:ro
volumes:
  static-content:
  media-content:
  certbotwww:
  certbotcerts: